In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

import warnings
warnings.filterwarnings('ignore')

sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

In [14]:

df = pd.read_csv('../data/insurance_data.csv', 
                 sep='|',          
                 low_memory=False)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())
df.head()

Shape: (3168, 52)

Columns:
['UnderwrittenCoverID', 'PolicyID', 'TransactionMonth', 'IsVATRegistered', 'Citizenship', 'LegalType', 'Title', 'Language', 'Bank', 'AccountType', 'MaritalStatus', 'Gender', 'Country', 'Province', 'PostalCode', 'MainCrestaZone', 'SubCrestaZone', 'ItemType', 'mmcode', 'VehicleType', 'RegistrationYear', 'make', 'Model', 'Cylinders', 'cubiccapacity', 'kilowatts', 'bodytype', 'NumberOfDoors', 'VehicleIntroDate', 'CustomValueEstimate', 'AlarmImmobiliser', 'TrackingDevice', 'CapitalOutstanding', 'NewVehicle', 'WrittenOff', 'Rebuilt', 'Converted', 'CrossBorder', 'NumberOfVehiclesInFleet', 'SumInsured', 'TermFrequency', 'CalculatedPremiumPerTerm', 'ExcessSelected', 'CoverCategory', 'CoverType', 'CoverGroup', 'Section', 'Product', 'StatutoryClass', 'StatutoryRiskType', 'TotalPremium', 'TotalClaims']

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0

In [15]:
# data overview
df.info()
df.describe(include='all').T

<class 'pandas.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 52 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   UnderwrittenCoverID       3168 non-null   int64
 1   PolicyID                  3168 non-null   int64
 2   TransactionMonth          3168 non-null   str
 3   IsVATRegistered           3168 non-null   bool
 4   Citizenship               3168 non-null   str
 5   LegalType                 3168 non-null   str
 6   Title                     3168 non-null   str
 7   Language                  3168 non-null   str
 8   Bank                      2592 non-null   str
 9   AccountType               2592 non-null   str
 10  MaritalStatus             3167 non-null   str
 11  Gender                    3167 non-null   str
 12  Country                   3167 non-null   str
 13  Province                  3167 non-null   str
 14  PostalCode                3167 non-null   float64
 15  MainCrestaZone            3167 non-null   str
 16  SubCrestaZone             3167 non-null   str
 17  ItemType                  3167 non-null   str
 18  mmcode                    3167 non-null   float64
 19  VehicleType               3167 non-null   str
 20  RegistrationYear          3167 non-null   float64
 21  make                      3167 non-null   str
 22  Model                     3167 non-null   str
 23  Cylinders                 3167 non-null   float64
 24  cubiccapacity             3167 non-null   float64
 25  kilowatts                 3167 non-null   float64
 26  bodytype                  3167 non-null   str
 27  NumberOfDoors             3167 non-null   float64
 28  VehicleIntroDate          3167 non-null   str
 29  CustomValueEstimate       1193 non-null   float64
 30  AlarmImmobiliser          3167 non-null   str
 31  TrackingDevice            3167 non-null   str
 32  CapitalOutstanding        3167 non-null   float64
 33  NewVehicle                2434 non-null   str
 34  WrittenOff                767 non-null    str
 35  Rebuilt                   767 non-null    str
 36  Converted                 767 non-null    str
 37  CrossBorder               0 non-null      float64
 38  NumberOfVehiclesInFleet   0 non-null      float64
 39  SumInsured                3167 non-null   float64
 40  TermFrequency             3167 non-null   str
 41  CalculatedPremiumPerTerm  3167 non-null   float64
 42  ExcessSelected            3167 non-null   str
 43  CoverCategory             3167 non-null   str
 44  CoverType                 3167 non-null   str
 45  CoverGroup                3167 non-null   str
 46  Section                   3167 non-null   str
 47  Product                   3167 non-null   str
 48  StatutoryClass            3167 non-null   str
 49  StatutoryRiskType         3167 non-null   str
 50  TotalPremium              3167 non-null   float64
 51  TotalClaims               3167 non-null   float64
dtypes: bool(1), float64(15), int64(2), str(34)
memory usage: 1.2 MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
UnderwrittenCoverID,3168.0,NaN,NaN,NaN,103559.749684,61557.049479,2438.0,50187.0,120088.0,139085.0,277829.0
PolicyID,3168.0,NaN,NaN,NaN,8224.786616,5625.745205,283.0,1064.0,8672.0,11719.0,21252.0
TransactionMonth,3168,19,2015-06-01 00:00:00,356,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IsVATRegistered,3168,2,False,2367,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Citizenship,3168,1,,3168,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LegalType,3168,2,Individual,1741,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Title,3168,3,Mr,1427,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Language,3168,1,English,3168,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Bank,2592,5,First National Bank,1211,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AccountType,2592,3,Current account,1948,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MaritalStatus,3167,1,Not specified,3167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Gender,3167,1,Not specified,3167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,3167,1,South Africa,3167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Province,3167,7,Gauteng,1710,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PostalCode,3167.0,NaN,NaN,NaN,2575.393432,1573.797847,122.0,1625.0,2007.0,4093.0,7784.0
MainCrestaZone,3167,9,Transvaal (all except Pretoria),894,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SubCrestaZone,3167,14,Rand East,667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ItemType,3167,1,Mobility - Motor,3167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mmcode,3167.0,NaN,NaN,NaN,51926346.249132,18114340.097078,4042080.0,50610300.0,60058415.0,60058419.0,65030720.0
VehicleType,3167,2,Passenger Vehicle,2748,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RegistrationYear,3167.0,NaN,NaN,NaN,2010.04168,3.408144,2004.0,2008.0,2010.0,2013.0,2015.0
make,3167,9,TOYOTA,1637,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Model,3167,25,QUANTUM 2.7 SESFIKILE 16s,422,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Cylinders,3167.0,NaN,NaN,NaN,4.347332,1.057407,3.0,4.0,4.0,4.0,10.0
cubiccapacity,3167.0,NaN,NaN,NaN,2407.972529,686.721721,996.0,1968.0,2521.0,2694.0,4921.0
kilowatts,3167.0,NaN,NaN,NaN,107.163877,32.500216,51.0,80.0,111.0,115.0,230.0
bodytype,3167,6,B/S,1563,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NumberOfDoors,3167.0,NaN,NaN,NaN,4.141459,0.704786,2.0,4.0,4.0,5.0,5.0
VehicleIntroDate,3167,21,4/2012,690,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomValueEstimate,1193.0,NaN,NaN,NaN,239132.497066,147681.556859,52700.0,140400.0,202900.0,392000.0,626084.0
AlarmImmobiliser,3167,1,Yes,3167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TrackingDevice,3167,2,No,2031,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CapitalOutstanding,3167.0,NaN,NaN,NaN,112397.330281,118814.399121,0.0,0.0,86300.0,178300.0,394500.0
NewVehicle,2434,1,More than 6 months,2434,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WrittenOff,767,1,No,767,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rebuilt,767,1,No,767,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Converted,767,1,No,767,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CrossBorder,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NumberOfVehiclesInFleet,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SumInsured,3167.0,NaN,NaN,NaN,611968.661696,1501279.970011,0.01,5000.0,7500.0,341400.0,5000000.0
TermFrequency,3167,1,Monthly,3167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CalculatedPremiumPerTerm,3167.0,NaN,NaN,NaN,128.272152,276.218128,0.3812,2.8752,8.7624,85.0,1694.8141
ExcessSelected,3167,8,No excess,2520,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CoverCategory,3167,19,Keys and Alarms,364,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CoverType,3167,14,Keys and Alarms,364,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CoverGroup,3167,6,Comprehensive - Taxi,2691,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Section,3167,3,Motor Comprehensive,2691,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product,3167,2,Mobility Commercial Cover: Monthly,1982,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StatutoryClass,3167,1,Commercial,3167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StatutoryRiskType,3167,1,IFRS Constant,3167,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TotalPremium,3167.0,NaN,NaN,NaN,75.404617,196.240108,0.0,0.0,2.882193,35.160702,1486.679035
TotalClaims,3167.0,NaN,NaN,NaN,42.994602,1108.372721,0.0,0.0,0.0,0.0,46492.211754